language: python
branches:
  only:
  - master
  - "/v\\d+\\.\\d+\\.\\d+([ab]\\d)?/"
sudo: false
matrix:
  include:
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install -U pip setuptools wheel tox-travis coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: aliman
  password:
    secure: XSHffe6SI/vg5POHxC3h2V8cP7sg4e7pWLVbc3BaL/j6+f4inIcay83IDbdSJKIj9prVIprnO+UMWWWnXqihvX0R7VpX6HxN7qlB+9sknYzfan99ItWSV0ZoQVb7xw1qgAnO3orRXBjW8rudjEs0RkliKSGZlOqlos2WoO9b26j9H1oqtgFrO699QVGgBJPqfp9z5zNvzCcqrs5v99O67arBt5F4t3utPxI6EnbGQd1BVUns+OUg/o1Mor0UU7EibO7SCxmUIQNLz2T2KNzcKPIGisYWwSU0LYfnbrHS/2UZPeQX3B+w0EplOwaZ78VVSfx4eqDJ0t4tsgn1yXSdIH8LwRuViIOfn+arbeX87MCikLLbQ08c3OIFhvuhGQeJ+ZJAyercuLGN3g3jAgZXeZ67lPHVUW2jIl7ovn5qEUZ7bFLfhglJ2IQHdavw3drYJ4RBlPC1nXrRM0Q7QTy6oLNXfnEUj1rzm9JQBgFqHHWIU4URvo5kTSKimt4xaHRujN8PLtExJzhsHzmaieK6KA1hBK77stfNt68QspnSx5Sfb6iF5hQTtfMJkTjoZ22CC8HEDvfLhXPB2a5/aDRV7oaaTjrBag8H3Hr6c1afPFipnanpfzyT7BFmBKNBcA1bELpvODg+pklj/c3OZJrf/J3kRFMN/FuQvsNCHZb5jBA=
  on:
    tags: true
  skip_existing: true
